-----------------------------------------------------------------------------
{-# LANGUAGE LambdaCase        #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
-----------------------------------------------------------------------------
-- | Golden tests: replay the fixtures generated by @tests\/golden\/gen.ts@
-- (which runs the real @\@xyflow\/system@ code) through the Haskell ports
-- and demand identical results — SVG paths byte-for-byte, numbers
-- exactly.
--
-- Regenerate the fixtures with @bun tests\/golden\/gen.ts@.
----------------------------------------------------------------------------
module Main where
-----------------------------------------------------------------------------
import           Control.Monad (forM_, unless)
import qualified Data.Map.Strict as M
import           Data.IORef
import           Data.List (sort)
import           Data.Maybe (fromMaybe)
import           Prelude
import           System.Exit (exitFailure)
-----------------------------------------------------------------------------
import           Miso.JSON (Value (..), decode)
import           Miso.String (MisoString, ms)
-----------------------------------------------------------------------------
import           Miso.Flow.Changes
import           Miso.Flow.Types
import           Miso.Flow.Utils.Edges
import           Miso.Flow.Utils.General
import           Miso.Flow.Utils.Graph
import           Miso.Flow.Utils.Marker
import           Miso.Flow.Utils.Store
-----------------------------------------------------------------------------
-- * Value plucking (fixtures are trusted; partiality is fine here)
-----------------------------------------------------------------------------
(!) :: Value -> MisoString -> Value
Object o ! k = fromMaybe (error ("missing key " <> show k)) (M.lookup k o)
v ! k = error ("not an object at key " <> show k <> ": " <> show v)
-----------------------------------------------------------------------------
opt :: Value -> MisoString -> Maybe Value
opt (Object o) k = case M.lookup k o of
  Just Null -> Nothing
  x -> x
opt _ _ = Nothing
-----------------------------------------------------------------------------
num :: Value -> Double
num (Number n) = n
num v = error ("not a number: " <> show v)
-----------------------------------------------------------------------------
str :: Value -> MisoString
str (String s) = s
str v = error ("not a string: " <> show v)
-----------------------------------------------------------------------------
bool :: Value -> Bool
bool (Bool b) = b
bool v = error ("not a bool: " <> show v)
-----------------------------------------------------------------------------
arr :: Value -> [Value]
arr (Array xs) = xs
arr v = error ("not an array: " <> show v)
-----------------------------------------------------------------------------
posOf :: Value -> Position
posOf v = fromMaybe (error "bad position") (positionFromText (str v))
-----------------------------------------------------------------------------
xyOf :: Value -> XYPosition
xyOf v = XYPosition (num (v ! "x")) (num (v ! "y"))
-----------------------------------------------------------------------------
rectOf :: Value -> Rect
rectOf v = Rect (num (v ! "x")) (num (v ! "y")) (num (v ! "width")) (num (v ! "height"))
-----------------------------------------------------------------------------
transformOf :: Value -> Transform
transformOf v = case arr v of
  [tx, ty, tz] -> Viewport (num tx) (num ty) (num tz)
  _ -> error "bad transform"
-----------------------------------------------------------------------------
-- * Harness
-----------------------------------------------------------------------------
type Failures = IORef [String]
-----------------------------------------------------------------------------
checkEq :: (Eq a, Show a) => Failures -> String -> a -> a -> IO ()
checkEq failures label expected actual =
  unless (expected == actual) $
    modifyIORef' failures (++ [ label <> "\n  expected: " <> show expected <> "\n  actual:   " <> show actual ])
-----------------------------------------------------------------------------
-- expected EdgePath from a fixture row (path/labelX/labelY/offsetX/offsetY)
expectedPath :: Value -> EdgePath
expectedPath v = EdgePath
  { edgePath = str (v ! "path")
  , edgePathLabelX = num (v ! "labelX")
  , edgePathLabelY = num (v ! "labelY")
  , edgePathOffsetX = num (v ! "offsetX")
  , edgePathOffsetY = num (v ! "offsetY")
  }
-----------------------------------------------------------------------------
main :: IO ()
main = do
  raw <- readFile "tests/golden/golden.json"
  let golden = fromMaybe (error "cannot parse golden.json") (decode (ms raw)) :: Value
  failures <- newIORef []
  let check :: (Eq a, Show a) => String -> a -> a -> IO ()
      check = checkEq failures
      section k = arr (golden ! k)

  -- bezier -------------------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "bezier")) $ \(i, c) ->
    check ("bezier[" <> show i <> "]") (expectedPath c) $
      getBezierPath (bezierPathParams (num (c ! "sx")) (num (c ! "sy")) (num (c ! "tx")) (num (c ! "ty")))
        { bezierSourcePosition = posOf (c ! "sp")
        , bezierTargetPosition = posOf (c ! "tp")
        , bezierCurvatureParam = num (c ! "curvature")
        }

  -- smoothstep ---------------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "smoothstep")) $ \(i, c) ->
    check ("smoothstep[" <> show i <> "]") (expectedPath c) $
      getSmoothStepPath (smoothStepPathParams (num (c ! "sx")) (num (c ! "sy")) (num (c ! "tx")) (num (c ! "ty")))
        { smoothSourcePosition = posOf (c ! "sp")
        , smoothTargetPosition = posOf (c ! "tp")
        , smoothBorderRadius = num (c ! "borderRadius")
        , smoothOffset = num (c ! "offset")
        , smoothStepPosition' = num (c ! "stepPosition")
        , smoothCenterX = num <$> opt c "centerX"
        , smoothCenterY = num <$> opt c "centerY"
        }

  -- straight -----------------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "straight")) $ \(i, c) ->
    check ("straight[" <> show i <> "]") (expectedPath c) $
      getStraightPath (num (c ! "sx")) (num (c ! "sy")) (num (c ! "tx")) (num (c ! "ty"))

  -- simple bezier ------------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "simplebezier")) $ \(i, c) ->
    check ("simplebezier[" <> show i <> "]") (expectedPath c) $
      getSimpleBezierPath
        (num (c ! "sx")) (num (c ! "sy")) (posOf (c ! "sp"))
        (num (c ! "tx")) (num (c ! "ty")) (posOf (c ! "tp"))

  -- edge center --------------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "edgeCenter")) $ \(i, c) ->
    check ("edgeCenter[" <> show i <> "]")
      (num (c ! "cx"), num (c ! "cy"), num (c ! "ox"), num (c ! "oy"))
      (getEdgeCenter (num (c ! "sx")) (num (c ! "sy")) (num (c ! "tx")) (num (c ! "ty")))

  -- viewport for bounds ------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "viewportForBounds")) $ \(i, c) -> do
    let out = c ! "out"
    check ("viewportForBounds[" <> show i <> "]")
      (Viewport (num (out ! "x")) (num (out ! "y")) (num (out ! "zoom")))
      (getViewportForBounds (rectOf (c ! "b")) (num (c ! "w")) (num (c ! "h"))
        (num (c ! "minZoom")) (num (c ! "maxZoom"))
        (PaddingUniform (PaddingRatio (num (c ! "padding")))))

  -- point conversions --------------------------------------------------
  forM_ (zip [0 :: Int ..] (section "pointToRenderer")) $ \(i, c) ->
    check ("pointToRenderer[" <> show i <> "]") (xyOf (c ! "out")) $
      pointToRendererPoint (xyOf (c ! "p")) (transformOf (c ! "t")) False (SnapGrid 1 1)
  forM_ (zip [0 :: Int ..] (section "pointToRendererSnapped")) $ \(i, c) -> do
    let g = case arr (c ! "snapGrid") of
          [gx, gy] -> SnapGrid (num gx) (num gy)
          _ -> error "bad snapGrid"
    check ("pointToRendererSnapped[" <> show i <> "]") (xyOf (c ! "out")) $
      pointToRendererPoint (xyOf (c ! "p")) (transformOf (c ! "t")) True g
  forM_ (zip [0 :: Int ..] (section "rendererToPoint")) $ \(i, c) ->
    check ("rendererToPoint[" <> show i <> "]") (xyOf (c ! "out")) $
      rendererPointToPoint (xyOf (c ! "p")) (transformOf (c ! "t"))

  -- snap / clamp / rect algebra ---------------------------------------
  forM_ (zip [0 :: Int ..] (section "snap")) $ \(i, c) -> do
    let g = case arr (c ! "g") of
          [gx, gy] -> SnapGrid (num gx) (num gy)
          _ -> error "bad grid"
    check ("snap[" <> show i <> "]") (xyOf (c ! "out")) (snapPosition (xyOf (c ! "p")) g)
  forM_ (zip [0 :: Int ..] (section "clamp")) $ \(i, c) -> do
    let extent = case arr (c ! "extent") of
          [lo, hi] -> case (arr lo, arr hi) of
            ([x1, y1], [x2, y2]) -> CoordinateExtent (num x1) (num y1) (num x2) (num y2)
            _ -> error "bad extent"
          _ -> error "bad extent"
        dim = Dimensions (num (c ! "dim" ! "width")) (num (c ! "dim" ! "height"))
    check ("clamp[" <> show i <> "]") (xyOf (c ! "out")) (clampPosition (xyOf (c ! "p")) extent dim)
  forM_ (zip [0 :: Int ..] (section "boundsOfRects")) $ \(i, c) ->
    check ("boundsOfRects[" <> show i <> "]") (rectOf (c ! "out"))
      (getBoundsOfRects (rectOf (c ! "a")) (rectOf (c ! "b")))
  forM_ (zip [0 :: Int ..] (section "overlap")) $ \(i, c) ->
    check ("overlap[" <> show i <> "]") (num (c ! "out"))
      (getOverlappingArea (rectOf (c ! "a")) (rectOf (c ! "b")))

  -- markers ------------------------------------------------------------
  let markerEdges :: [Edge ()]
      markerEdges =
        [ (edge "e1" "1" "2") { edgeMarkerEnd = Just (Marker (edgeMarker MarkerArrowClosed)) }
        , (edge "e2" "2" "3")
            { edgeMarkerStart = Just (Marker (edgeMarker MarkerArrow)
                { markerColor = Just "#f00", markerStrokeWidth = Just 2 }) }
        , (edge "e3" "3" "4") { edgeMarkerEnd = Just (Marker (edgeMarker MarkerArrowClosed)) }
        , (edge "e4" "4" "5") { edgeMarkerEnd = Just (MarkerRef "my-marker-ref") }
        , (edge "e5" "5" "6")
            { edgeMarkerEnd = Just (Marker (edgeMarker MarkerArrow)
                { markerWidth = Just 30, markerHeight = Just 20
                , markerUnits = Just "userSpaceOnUse", markerOrient = Just "auto" }) }
        ]
      markerProject MarkerProps {..} =
        ( markerPropsId
        , markerColor markerPropsMarker
        , markerTypeToText (markerType markerPropsMarker)
        , markerWidth markerPropsMarker
        , markerHeight markerPropsMarker
        , markerUnits markerPropsMarker
        , markerOrient markerPropsMarker
        , markerStrokeWidth markerPropsMarker
        )
      markerFixture v =
        ( str (v ! "id")
        , str <$> opt v "color"
        , str (v ! "type")
        , num <$> opt v "width"
        , num <$> opt v "height"
        , str <$> opt v "markerUnits"
        , str <$> opt v "orient"
        , num <$> opt v "strokeWidth"
        )
  check "markers.ids"
    (map markerFixture (arr (golden ! "markers" ! "ids")))
    (map markerProject (createMarkerIds markerEdges (Just "flow-a") (Just "#888") Nothing Nothing))
  forM_ (zip [0 :: Int ..] (arr (golden ! "markers" ! "single"))) $ \(i, c) -> do
    let m = c ! "m"
        marker = (edgeMarker (if str (m ! "type") == "arrow" then MarkerArrow else MarkerArrowClosed))
          { markerColor = str <$> opt m "color"
          , markerStrokeWidth = num <$> opt m "strokeWidth"
          }
    check ("markers.single[" <> show i <> "]") (str (c ! "out"))
      (getMarkerId (Just (Marker marker)) (str <$> opt c "flowId"))

  -- addEdge / getEdgeId ------------------------------------------------
  let baseEdges = [ edge "e1-2" "1" "2" ] :: [Edge ()]
      connOf v = Connection (str (v ! "source")) (str (v ! "target"))
        (str <$> opt v "sourceHandle") (str <$> opt v "targetHandle")
  forM_ (zip [0 :: Int ..] (section "addEdgeCases")) $ \(i, c) ->
    check ("addEdge[" <> show i <> "]") (map str (arr (c ! "out")))
      (map edgeId (addEdge (connOf (c ! "conn")) baseEdges))
  forM_ (zip [0 :: Int ..] (section "edgeIds")) $ \(i, c) ->
    check ("edgeIds[" <> show i <> "]") (str (c ! "out")) (getEdgeId (connOf c))

  -- adoptUserNodes -----------------------------------------------------
  let measuredNode i p w h = (node i p ())
        { nodeMeasured = Just (Measured (Just w) (Just h)) }
      userNodes =
        [ measuredNode "1" (xy 0 0) 100 40
        , (measuredNode "2" (xy 250 150) 120 50) { nodeSelected = True }
        , (measuredNode "3" (xy (-80.5) 60) 80 30) { nodeZIndex = Just 7 }
        , measuredNode "p" (xy 400 400) 300 200
        , (measuredNode "c1" (xy 20 30) 50 20) { nodeParentId = Just "p" }
        , (measuredNode "c2" (xy 10 10) 40 40)
            { nodeParentId = Just "p", nodeOrigin = Just (NodeOrigin 0.5 0.5) }
        ]
      (nodeLookup, _parentLookup, _) =
        adoptUserNodes userNodes M.empty defaultUpdateNodesOptions
      adoptProject n =
        ( nodeId (internalUserNode n)
        , xyX (internalPositionAbsolute n)
        , xyY (internalPositionAbsolute n)
        , internalZ n
        )
      adoptFixture v = (str (v ! "id"), num (v ! "x"), num (v ! "y"), num (v ! "z"))
  check "adopt"
    (sort (map adoptFixture (section "adopt")))
    (sort (map adoptProject (M.elems nodeLookup)))

  -- graph --------------------------------------------------------------
  let graphFix = golden ! "graph"
      graphEdges = [ edge "e1-2" "1" "2", edge "e2-3" "2" "3", edge "e1-3" "1" "3" ] :: [Edge ()]
  check "graph.nodesBounds" (rectOf (graphFix ! "nodesBounds"))
    (getNodesBounds (take 3 userNodes) defaultOrigin)
  check "graph.nodesInside" (map str (arr (graphFix ! "nodesInside")))
    (sort (map (nodeId . internalUserNode)
      (getNodesInside nodeLookup (Rect (-100) (-10) 400 260) (Viewport 0 0 1) False False)))
  check "graph.nodesInsidePartial" (map str (arr (graphFix ! "nodesInsidePartial")))
    (sort (map (nodeId . internalUserNode)
      (getNodesInside nodeLookup (Rect (-100) (-10) 400 260) (Viewport 0 0 1) True False)))
  check "graph.connected" (map str (arr (graphFix ! "connected")))
    (sort (map edgeId (getConnectedEdges [userNodes !! 1] graphEdges)))
  check "graph.incomers" (map str (arr (graphFix ! "incomers")))
    (sort (map nodeId (getIncomers "3" userNodes graphEdges)))
  check "graph.outgoers" (map str (arr (graphFix ! "outgoers")))
    (sort (map nodeId (getOutgoers "1" userNodes graphEdges)))

  -- applyNodeChanges ---------------------------------------------------
  let changeNodes =
        [ node "1" (xy 0 0) ()
        , node "2" (xy 100 100) ()
        , node "3" (xy 200 200) ()
        ] :: [Node ()]
      nodeChangeOf v = case str (v ! "type") of
        "position" -> NodePositionChange (str (v ! "id"))
          (xyOf <$> opt v "position") Nothing (bool <$> opt v "dragging")
        "dimensions" -> NodeDimensionChange (str (v ! "id"))
          ((\d -> Dimensions (num (d ! "width")) (num (d ! "height"))) <$> opt v "dimensions")
          (bool <$> opt v "resizing")
          (case opt v "setAttributes" of
             Just (Bool True) -> SetAttributesBoth
             Just (String "width") -> SetAttributesWidth
             Just (String "height") -> SetAttributesHeight
             _ -> SetAttributesNone)
        "select" -> NodeSelectionChange (str (v ! "id")) (bool (v ! "selected"))
        "remove" -> NodeRemoveChange (str (v ! "id"))
        "add" -> NodeAddChange (nodeOf (v ! "item")) (round . num <$> opt v "index")
        "replace" -> NodeReplaceChange (str (v ! "id")) (nodeOf (v ! "item"))
        t -> error ("unknown node change: " <> show t)
      nodeOf v = node (str (v ! "id")) (xyOf (v ! "position")) ()
      nodeProject n =
        ( nodeId n, xyX (nodePosition n), xyY (nodePosition n)
        , nodeSelected n, nodeWidth n, nodeHeight n
        , measuredWidth =<< nodeMeasured n, measuredHeight =<< nodeMeasured n
        , nodeResizing n
        )
      nodeOutFixture v =
        ( str (v ! "id"), num (v ! "x"), num (v ! "y")
        , maybe False bool (opt v "selected"), num <$> opt v "width", num <$> opt v "height"
        , num <$> opt v "measuredW", num <$> opt v "measuredH"
        , maybe False bool (opt v "resizing")
        )
  forM_ (zip [0 :: Int ..] (section "nodeChangeCases")) $ \(i, c) ->
    check ("nodeChanges[" <> show i <> "]")
      (map nodeOutFixture (arr (c ! "out")))
      (map nodeProject (applyNodeChanges (map nodeChangeOf (arr (c ! "changes"))) changeNodes))

  -- applyEdgeChanges ---------------------------------------------------
  let changeEdges =
        [ edge "e1" "1" "2"
        , (edge "e2" "2" "3") { edgeSelected = True }
        ] :: [Edge ()]
      edgeChangeOf v = case str (v ! "type") of
        "select" -> EdgeSelectionChange (str (v ! "id")) (bool (v ! "selected"))
        "remove" -> EdgeRemoveChange (str (v ! "id"))
        "add" -> EdgeAddChange
          (edge (str (v ! "item" ! "id")) (str (v ! "item" ! "source")) (str (v ! "item" ! "target")))
          (round . num <$> opt v "index")
        t -> error ("unknown edge change: " <> show t)
      edgeProject e = (edgeId e, edgeSelected e)
      edgeOutFixture v = (str (v ! "id"), maybe False bool (opt v "selected"))
  forM_ (zip [0 :: Int ..] (section "edgeChangeCases")) $ \(i, c) ->
    check ("edgeChanges[" <> show i <> "]")
      (map edgeOutFixture (arr (c ! "out")))
      (map edgeProject (applyEdgeChanges (map edgeChangeOf (arr (c ! "changes"))) changeEdges))

  -- report -------------------------------------------------------------
  failed <- readIORef failures
  let total = length (section "bezier") + length (section "smoothstep")
            + length (section "straight") + length (section "simplebezier")
  case failed of
    [] -> putStrLn ("golden: all sections passed (" <> show total <> " path cases + geometry/store/changes)")
    fs -> do
      forM_ (take 25 fs) (putStrLn . ("FAIL " <>))
      putStrLn (show (length fs) <> " failures")
      exitFailure
